apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cert-manager
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cert-manager: enabled
  repoURL: https://charts.jetstack.io
  chartName: cert-manager
  namespace: cert-manager
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
  reconcileStrategy: InstallOnce
  releaseName: cert-manager
  valuesTemplate: |
    installCRDs: true
