apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: fluxcd-sync
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      fluxcd-mgmt-sync: enabled
  repoURL: https://fluxcd-community.github.io/helm-charts
  chartName: flux2-sync
  namespace: flux-system
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
  reconcileStrategy: InstallOnce
  releaseName: flux2-sync
  valuesTemplate: |
    gitRepository:
      spec:
        ref:
          branch: main
        url: https://github.com/simonkran/capi-mgmt
    kustomization:
      spec:
        path: ./mgmt/dev/mgmt-0
