apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: hetzner-ccm
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      hetzner-ccm: enabled
  repoURL: https://charts.hetzner.cloud
  chartName: hcloud-cloud-controller-manager
  namespace: kube-system
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
  reconcileStrategy: InstallOnce
  releaseName: hetzner-ccm
  valuesTemplate: |
    env:
      - name: HCLOUD_TOKEN
        valueFrom:
          secretKeyRef:
            name: hetzner
            key: hcloud
    # Update network name in 1Password after new cluster deployment
    # env:
    #   - name: HCLOUD_NETWORK
    #     valueFrom:
    #       secretKeyRef:
    #         name: hetzner
    #         key: network
