---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: ${CLUSTER_NAME}-flux-sync
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
  repoURL: https://fluxcd-community.github.io/helm-charts
  chartName: flux2-sync
  namespace: flux-system
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
  reconcileStrategy: InstallOnce
  releaseName: ${CLUSTER_NAME}-flux-sync
  valuesTemplate: |
    gitRepository:
      spec:
        ref:
          branch: ${GIT_BRANCH:=main}
        url: https://github.com/${GIT_USER}/${GIT_REPO}
    kustomization:
      spec:
        path: ${KS_PATH}
