---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CLUSTER_NAME}-flux-gitrepository
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
data:
  gitrepository.yaml: |
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    metadata:
      name: ${CLUSTER_NAME}-apps
      namespace: flux-system
    spec:
      interval: 5m
      ref:
        branch: ${GIT_BRANCH:=main}
      timeout: 60s
      url: https://github.com/${GIT_USER}/${GIT_REPO}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CLUSTER_NAME}-flux-kustomization
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
data:
  kustomization.yaml: |
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: ${CLUSTER_NAME}-apps
      namespace: flux-system
    spec:
      force: false
      interval: 5m
      path: ${KS_PATH}
      prune: true
      sourceRef:
        kind: GitRepository
        name: ${CLUSTER_NAME}-apps
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: ${CLUSTER_NAME}-flux-sync
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
  resources:
    - kind: ConfigMap
      name: ${CLUSTER_NAME}-flux-gitrepository
    - kind: ConfigMap
      name: ${CLUSTER_NAME}-flux-kustomization
  strategy: ApplyOnce
