apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: capi-mgmt
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/simonkran/capi-mgmt
